Repository SSUMC-8th/Spring_Boot_B, pull requests merged in 2025-05, with the labels that each got.

#14 [Baguette-bbang] Chapter 5. JPA 기초 및 프로젝트 구조
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/domain/Alarm.java
  src/main/java/umc/study/domain/AlarmReference.java
  src/main/java/umc/study/domain/AlarmSetting.java
  src/main/java/umc/study/domain/Area.java
  src/main/java/umc/study/domain/AreaCompletion.java
  src/main/java/umc/study/domain/AreaReward.java
  src/main/java/umc/study/domain/AuthInformation.java
  src/main/java/umc/study/domain/Image.java
  src/main/java/umc/study/domain/Inquiry.java
  src/main/java/umc/study/domain/InquiryReply.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/PhoneVerification.java
  src/main/java/umc/study/domain/Point.java
  src/main/java/umc/study/domain/Preference.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewReply.java
  src/main/java/umc/study/domain/Role.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/StoreCategory.java
  src/main/java/umc/study/domain/StoreMetrics.java
  src/main/java/umc/study/domain/User.java
  src/main/java/umc/study/domain/UserMission.java
  src/main/java/umc/study/domain/UserPreference.java
  src/main/java/umc/study/domain/UserPreferenceId.java
  src/main/java/umc/study/domain/UserRole.java
  src/main/java/umc/study/domain/UserRoleId.java
  src/main/java/umc/study/domain/enums/AlarmType.java
  src/main/java/umc/study/domain/enums/AuthType.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/InquiryStatus.java
  src/main/java/umc/study/domain/enums/InquiryType.java
  src/main/java/umc/study/domain/enums/MemberStatus.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/OwnerType.java
  src/main/java/umc/study/domain/enums/PointReason.java
  src/main/java/umc/study/domain/enums/PointStatus.java
  src/main/java/umc/study/domain/enums/ReferenceType.java
  src/main/java/umc/study/domain/enums/RewardType.java
  src/main/java/umc/study/domain/enums/RoleName.java
  src/main/java/umc/study/domain/enums/SocialType.java
  src/main/java/umc/study/domain/enums/UserMissionStatus.java
  src/main/resources/application.yml
  src/test/java/umc/study/ApplicationTests.java
Labels: ✨ Chapter05

#17 [Richard] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewImage.java
  src/main/generated/umc/spring/domain/QSalesTime.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberFood.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberTerms.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/storeRepository/StoreRepository.java
  src/main/java/umc/spring/repository/storeRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/storeRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/storeService/StoreQueryService.java
  src/main/java/umc/spring/service/storeService/StoreQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#21 Baguette bbang/#20
  .gitignore
  build.gradle
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/dto/AvailableMissionDto.java
  src/main/java/umc/study/dto/MyPageDto.java
  src/main/java/umc/study/dto/UserMissionDto.java
  src/main/java/umc/study/repository/MissionQueryRepository.java
  src/main/java/umc/study/repository/ReviewRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/repository/UserMissionQueryRepository.java
  src/main/java/umc/study/repository/UserQueryRepository.java
  src/main/java/umc/study/service/ReviewCommandService.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#19 [Vega] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/study/domain/QAlert.java
  src/main/generated/umc/study/domain/QBusinessHours.java
  src/main/generated/umc/study/domain/QFoods.java
  src/main/generated/umc/study/domain/QMember.java
  src/main/generated/umc/study/domain/QMission.java
  src/main/generated/umc/study/domain/QRegion.java
  src/main/generated/umc/study/domain/QReview.java
  src/main/generated/umc/study/domain/QReviewImage.java
  src/main/generated/umc/study/domain/QShop.java
  src/main/generated/umc/study/domain/common/QBaseEntity.java
  src/main/generated/umc/study/domain/mapping/QMemberSelectFoods.java
  src/main/generated/umc/study/domain/mapping/QMissionAssignment.java
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/Shop.java
  src/main/java/umc/study/repository/ShopRepository/ShopRepository.java
  src/main/java/umc/study/repository/ShopRepository/ShopRepositoryCustom.java
  src/main/java/umc/study/repository/ShopRepository/ShopRepositoryImpl.java
  src/main/java/umc/study/service/ShopService/ShopQueryService.java
  src/main/java/umc/study/service/ShopService/ShopQueryServiceImpl.java
Labels: ✨ Chapter06

#25 [Richard] Chapter 7. API응답 통일 & 에러 핸들러
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/BaseCode.java
  src/main/java/umc/spring/apiPayload/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/repository/memberRepository/MemberRepository.java
  src/main/java/umc/spring/service/storeService/StoreQueryService.java
  src/main/java/umc/spring/service/storeService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/service/tempService/TempQueryService.java
  src/main/java/umc/spring/service/tempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#27 [Baguette-bbang] Chapter 7. API응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/apiPayload/exception/GeneralException.java
  src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/dto/TempResponse.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
Labels: ✨ Chapter07

#23 [Vega] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/exception/ExceptionAdvice.java
  src/main/java/umc/study/exception/GeneralException.java
  src/main/java/umc/study/exception/handler/TempHandler.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/umc/study/service/MemberSerivce/MemberService.java
  src/main/java/umc/study/service/MissionService/MissionService.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: ✨ Chapter07

#31 [Vega] Chapter 8. API & Swagger & Annotation
  build.gradle
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/config/SwaggerConfig.java
  src/main/java/umc/study/converter/MemberConverter.java
  src/main/java/umc/study/converter/MemberSelectFoodsConverter.java
  src/main/java/umc/study/converter/MissionAssignConverter.java
  src/main/java/umc/study/converter/MissionConverter.java
  src/main/java/umc/study/converter/RegionShopConverter.java
  src/main/java/umc/study/converter/ReviewConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/mapping/MemberSelectFoods.java
  src/main/java/umc/study/domain/mapping/MissionAssignment.java
  src/main/java/umc/study/exception/handler/FoodsHandler.java
  src/main/java/umc/study/exception/handler/GeneralHandler.java
  src/main/java/umc/study/repository/FoodsRepository.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/repository/MissionAssignmentRepository.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/RegionRepository.java
  src/main/java/umc/study/repository/ReviewRepository.java
  src/main/java/umc/study/repository/ShopRepository/ShopRepository.java
  src/main/java/umc/study/service/MemberSerivce/MemberService.java
  src/main/java/umc/study/service/MissionAssignmentService.java
  src/main/java/umc/study/service/MissionService/MissionService.java
  src/main/java/umc/study/service/ReviewService/ReviewService.java
  src/main/java/umc/study/service/ShopService/ShopService.java
  src/main/java/umc/study/validation/annotation/AssignMission.java
  src/main/java/umc/study/validation/annotation/ExistCategories.java
  src/main/java/umc/study/validation/annotation/ExistShop.java
  src/main/java/umc/study/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/study/validation/validator/MissionAssignValidator.java
  src/main/java/umc/study/validation/validator/ShopExistValidator.java
  src/main/java/umc/study/web/controller/MemberRestController.java
  src/main/java/umc/study/web/controller/MissionRestController.java
  src/main/java/umc/study/web/controller/ShopRestController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/java/umc/study/web/dto/MemberResponseDTO.java
  src/main/java/umc/study/web/dto/MissionChallengeRequestDTO.java
  src/main/java/umc/study/web/dto/MissionChallengeResponseDTO.java
  src/main/java/umc/study/web/dto/MissionRequestDTO.java
  src/main/java/umc/study/web/dto/MissionResponseDTO.java
  src/main/java/umc/study/web/dto/RegionShopRequestDTO.java
  src/main/java/umc/study/web/dto/RegionShopResponseDTO.java
  src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08
